import { existsSync, readFileSync, readdirSync } from "node:fs";
import path from "node:path";

/**
 * Structural validation of the offline sample report required for the AppSource
 * submission. The project is generated by `scripts/build-sample-report.mjs`; these tests
 * assert the committed result really is a valid, fully offline PBIP project bound to this
 * visual.
 */

const root = path.resolve(__dirname, "..");
const SAMPLE_SLUG = "AtlynSample";
const SAMPLE_ROOT = path.join(root, "samples");
const REPORT_ROOT = path.join(SAMPLE_ROOT, `${SAMPLE_SLUG}.Report`);
const MODEL_ROOT = path.join(SAMPLE_ROOT, `${SAMPLE_SLUG}.SemanticModel`);
const TABLE_NAME = "Observations";
const GUID = "atlynControlChartA1B2C3D4E5F6G7H8I9J0";

const readJson = <T>(...segments: string[]): T => (
    JSON.parse(readFileSync(path.join(...segments), "utf8")) as T
);

const capabilities = readJson<{ dataRoles: Array<{ name: string }> }>(root, "capabilities.json");
const roleNames = new Set(capabilities.dataRoles.map((role) => role.name));

function findVisualFile(): string {
    const pagesRoot = path.join(REPORT_ROOT, "definition", "pages");
    const pageIds = readdirSync(pagesRoot, { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => entry.name);
    expect(pageIds).toHaveLength(1);

    const visualsRoot = path.join(pagesRoot, pageIds[0], "visuals");
    const visualIds = readdirSync(visualsRoot, { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => entry.name);
    expect(visualIds).toHaveLength(1);

    return path.join(visualsRoot, visualIds[0], "visual.json");
}

describe("offline sample report project", () => {
    test("ships every required PBIP, PBIR, and TMDL part", () => {
        [
            [SAMPLE_ROOT, `${SAMPLE_SLUG}.pbip`],
            [SAMPLE_ROOT, "README.md"],
            [REPORT_ROOT, ".platform"],
            [REPORT_ROOT, "definition.pbir"],
            [REPORT_ROOT, "definition", "version.json"],
            [REPORT_ROOT, "definition", "report.json"],
            [REPORT_ROOT, "definition", "pages", "pages.json"],
            [MODEL_ROOT, ".platform"],
            [MODEL_ROOT, "definition.pbism"],
            [MODEL_ROOT, "definition", "database.tmdl"],
            [MODEL_ROOT, "definition", "model.tmdl"],
            [MODEL_ROOT, "definition", "tables", `${TABLE_NAME}.tmdl`]
        ].forEach((segments) => expect(existsSync(path.join(...segments))).toBe(true));

        expect(existsSync(findVisualFile())).toBe(true);
    });

    test("points the PBIP and PBIR at the report and semantic model folders", () => {
        const pbip = readJson<{ version: string; artifacts: Array<{ report: { path: string } }> }>(
            SAMPLE_ROOT,
            `${SAMPLE_SLUG}.pbip`
        );
        expect(pbip.artifacts).toEqual([{ report: { path: `${SAMPLE_SLUG}.Report` } }]);

        const pbir = readJson<{ version: string; datasetReference: { byPath: { path: string } } }>(
            REPORT_ROOT,
            "definition.pbir"
        );
        // 1.0 selects the legacy PBIR-Legacy/TMSL formats; the definition/ folder layout needs 4.0+.
        expect(pbir.version).toBe("4.0");
        expect(pbir.datasetReference.byPath.path).toBe(`../${SAMPLE_SLUG}.SemanticModel`);

        const pbism = readJson<{ version: string }>(MODEL_ROOT, "definition.pbism");
        expect(pbism.version).toBe("4.2");
    });

    test("binds the visual to the frozen GUID using only declared data roles", () => {
        const visual = readJson<{
            name: string;
            visual: {
                visualType: string;
                query: { queryState: Record<string, { projections: Array<Record<string, unknown>> }> };
            };
        }>(findVisualFile());

        expect(visual.visual.visualType).toBe(GUID);

        const queryState = visual.visual.query.queryState;
        const stateKeys = Object.keys(queryState);
        expect(stateKeys).toEqual(["Time", "Value"]);
        stateKeys.forEach((key) => expect(roleNames.has(key)).toBe(true));
        stateKeys.forEach((key) => expect(queryState[key].projections.length).toBeGreaterThan(0));
    });

    test("projects the subgroup as a raw column and the value as a single aggregate", () => {
        const contents = readFileSync(findVisualFile(), "utf8");
        expect(contents).toContain(`"Entity": "${TABLE_NAME}"`);
        expect(contents).toContain('"Property": "Day"');
        expect(contents).toContain('"Property": "Minutes"');
        // capabilities.json declares Value as a Measure role, so it is projected the way Power BI
        // Desktop writes a numeric column dropped into a measure well: Sum over one row per day.
        expect(contents).toContain(`"queryRef": "Sum(${TABLE_NAME}.Minutes)"`);
        expect(contents).toContain(`"queryRef": "${TABLE_NAME}.Day"`);
    });

    test("embeds the built visual instead of resolving it from AppSource", () => {
        const report = readJson<{
            publicCustomVisuals?: string[];
            resourcePackages: Array<{
                name: string;
                type: string;
                items: Array<{ name: string; path: string; type: string }>;
            }>;
        }>(REPORT_ROOT, "definition", "report.json");

        expect(report.publicCustomVisuals).toBeUndefined();

        const customVisual = report.resourcePackages.find((entry) => entry.type === "CustomVisual");
        expect(customVisual).toBeDefined();
        expect(customVisual?.name).toBe(GUID);
        expect(customVisual?.items).toEqual([{
            name: `${GUID}.pbiviz.json`,
            path: `${GUID}.pbiviz.json`,
            type: "CustomVisualMetadata"
        }]);

        const embeddedRoot = path.join(REPORT_ROOT, "CustomVisuals", GUID);
        expect(existsSync(path.join(embeddedRoot, "package.json"))).toBe(true);

        const resourcePath = path.join(embeddedRoot, "resources", `${GUID}.pbiviz.json`);
        expect(existsSync(resourcePath)).toBe(true);

        const resource = JSON.parse(readFileSync(resourcePath, "utf8")) as {
            visual: { guid: string; version: string };
            content: { js: string; css: string };
        };
        const pbiviz = readJson<{ visual: { version: string } }>(root, "pbiviz.json");
        expect(resource.visual.guid).toBe(GUID);
        expect(resource.visual.version).toBe(pbiviz.visual.version);
        expect(resource.content.js.length).toBeGreaterThan(50000);
        // A packaged visual with no CSS renders unstyled in Desktop.
        expect(resource.content.css.length).toBeGreaterThan(1000);
    });

    test("loads its data from a DAX calculated table with no data source at all", () => {
        const definitionRoot = path.join(MODEL_ROOT, "definition");
        const tmdl = readFileSync(path.join(definitionRoot, "tables", `${TABLE_NAME}.tmdl`), "utf8");

        [
            "Sql.Database",
            "Web.Contents",
            "File.Contents",
            "Csv.Document",
            "Excel.Workbook",
            "OData.Feed",
            "Folder.Files",
            "SharePoint",
            "Odbc."
        ].forEach((token) => expect(tmdl).not.toContain(token));
        expect(tmdl).not.toMatch(/\bhttps?:\/\//);

        // A calculated table has no data source object, unlike a Power Query partition.
        expect(tmdl).toContain("= calculated");
        expect(tmdl).toContain("mode: import");
        expect(tmdl).toContain("DATATABLE(");
        expect(tmdl).toContain('"Day", STRING');
        expect(tmdl).toContain('"Minutes", DOUBLE');

        const modelFiles = readdirSync(definitionRoot, { withFileTypes: true })
            .filter((entry) => entry.isFile())
            .map((entry) => entry.name)
            .sort();
        expect(modelFiles).toEqual(["database.tmdl", "model.tmdl"]);

        const everyTmdl = [
            path.join(definitionRoot, "database.tmdl"),
            path.join(definitionRoot, "model.tmdl"),
            path.join(definitionRoot, "tables", `${TABLE_NAME}.tmdl`)
        ].map((file) => readFileSync(file, "utf8")).join("\n");

        // No Power Query partition, no shared expressions, no data source declarations.
        expect(everyTmdl).not.toMatch(/^\s*partition .+ = m$/m);
        expect(everyTmdl).not.toMatch(/^\s*expression /m);
        expect(everyTmdl).not.toMatch(/^\s*dataSource /m);
        expect(everyTmdl).toContain("compatibilityLevel: 1550");
        expect(everyTmdl).toContain("culture: en-US");
        expect(everyTmdl).toContain(`ref table ${TABLE_NAME}`);
    });

    test("declares no resource package that does not exist on disk", () => {
        /*
         * This is the defect that stopped the project opening in Power BI Desktop: report.json
         * declared a SharedResources package pointing at BaseThemes/CY24SU10.json, which the
         * project does not contain. It was schema-valid the whole time - a JSON schema
         * constrains shape, not existence - so Desktop reported "Issues were found" and fell
         * back to an empty report.
         *
         * CY24SU10 is a base theme built into Desktop. themeCollection may reference it;
         * resourcePackages may not, because that claims it ships as a file in the report.
         */
        const report = readJson<{
            themeCollection: { baseTheme: { name: string; type: string } };
            resourcePackages: Array<{
                name: string;
                type: string;
                items: Array<{ name: string; path: string; type: string }>;
            }>;
        }>(REPORT_ROOT, "definition", "report.json");

        expect(report.themeCollection.baseTheme.name).toBe("CY24SU10");
        expect(report.resourcePackages.map((entry) => entry.type)).toEqual(["CustomVisual"]);

        for (const pkg of report.resourcePackages) {
            for (const item of pkg.items) {
                const candidates = pkg.type === "CustomVisual"
                    ? [path.join(REPORT_ROOT, "CustomVisuals", pkg.name, "resources", item.path)]
                    : [
                        path.join(REPORT_ROOT, "StaticResources", pkg.name, item.path),
                        path.join(REPORT_ROOT, item.path)
                    ];
                expect(candidates.some((candidate) => existsSync(candidate))).toBe(true);
            }
        }
    });

    test("uses the schema versions Power BI Desktop 2.150 is known to open", () => {
        // Every one of these URLs resolves, but only this combination has been observed to
        // open in the product, so it is pinned rather than left to drift upward.
        const schemaOf = (...segments: string[]) =>
            readJson<{ $schema: string }>(...segments).$schema;

        expect(schemaOf(SAMPLE_ROOT, `${SAMPLE_SLUG}.pbip`))
            .toContain("/fabric/pbip/pbipProperties/1.0.0/");
        expect(schemaOf(REPORT_ROOT, "definition", "report.json"))
            .toContain("/report/2.1.0/");
        expect(schemaOf(REPORT_ROOT, "definition", "pages", "pages.json"))
            .toContain("/pagesMetadata/1.1.0/");
        expect(schemaOf(findVisualFile()))
            .toContain("/visualContainer/2.7.0/");

        const pagesRoot = path.join(REPORT_ROOT, "definition", "pages");
        const pageId = readdirSync(pagesRoot, { withFileTypes: true })
            .filter((entry) => entry.isDirectory())[0].name;
        expect(schemaOf(pagesRoot, pageId, "page.json")).toContain("/page/2.1.0/");

        // version.json is pattern-constrained to ^[1-9][0-9]*\.(0|[1-9][0-9]*)\.0$
        const version = readJson<{ version: string }>(REPORT_ROOT, "definition", "version.json").version;
        expect(version).toMatch(/^[1-9][0-9]*\.(0|[1-9][0-9]*)\.0$/);
    });

    test("carries a single ordered observation per subgroup with a genuine special cause", () => {
        const tmdl = readFileSync(
            path.join(MODEL_ROOT, "definition", "tables", `${TABLE_NAME}.tmdl`),
            "utf8"
        );
        const rows = tmdl.split(/\r?\n/)
            .map((line) => /^\{"(\d{4}-\d{2}-\d{2})", (-?\d+\.\d+), "([^"]+)", (\d+), (\d+)\},?$/
                .exec(line.trim()))
            .filter((match): match is RegExpExecArray => Boolean(match))
            .map((match) => ({ day: match[1], minutes: Number(match[2]) }));

        expect(rows).toHaveLength(36);
        expect(new Set(rows.map((row) => row.day)).size).toBe(rows.length);
        const sorted = [...rows].map((row) => row.day).sort();
        expect(rows.map((row) => row.day)).toEqual(sorted);

        // The screenshots and the sample report must show the same special cause.
        const values = rows.map((row) => row.minutes);
        expect(Math.max(...values)).toBe(39.8);
        expect(values[values.length - 1]).toBe(37.4);
    });
});
